# Generated by Django 5.2.8 on 2025-12-01 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises_data',
            field=models.TextField(default='[]', help_text='JSON com lista de exercicios, series, reps e carga'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='feeling',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(default='Treino do Dia', max_length=200),
        ),
    ]
