# Generated by Django 5.2.8 on 2025-12-01 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_workouttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exercise_type', models.CharField(choices=[('strength', 'Musculação (Carga/Reps)'), ('cardio', 'Cardio (Tempo/Distância)'), ('calisthenics', 'Calistenia (Apenas Reps/Tempo)')], default='strength', max_length=20)),
                ('muscle_group', models.CharField(blank=True, help_text='Ex: Peito, Costas, Pernas', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
