# Generated by Django 5.2.8 on 2025-12-05 03:09

from django.db import migrations


def add_abdominal_exercises(apps, schema_editor):
    """Adiciona exercícios básicos de abdominal ao banco de dados"""
    Exercise = apps.get_model('tracker', 'Exercise')

    # Lista de exercícios de abdominal/core para adicionar
    abs_exercises = [
        {'name': 'Abdominal (Crunch)', 'type': 'calisthenics', 'muscle': 'Core'},
        {'name': 'Sit-up', 'type': 'calisthenics', 'muscle': 'Core'},
        {'name': 'Abdominal Supra', 'type': 'calisthenics', 'muscle': 'Core'},
        {'name': 'Abdominal Infra (Leg Raise)', 'type': 'calisthenics', 'muscle': 'Core'},
        {'name': 'Abdominal Oblíquo', 'type': 'calisthenics', 'muscle': 'Core'},
        {'name': 'Prancha Lateral (Side Plank)', 'type': 'calisthenics', 'muscle': 'Core'},
        {'name': 'Mountain Climbers', 'type': 'calisthenics', 'muscle': 'Core'},
        {'name': 'Russian Twist', 'type': 'calisthenics', 'muscle': 'Core'},
        {'name': 'Bicicleta (Bicycle Crunch)', 'type': 'calisthenics', 'muscle': 'Core'},
    ]

    # Criar os exercícios (globais, user=None)
    for ex in abs_exercises:
        Exercise.objects.get_or_create(
            name=ex['name'],
            user=None,  # Exercício global
            defaults={
                'exercise_type': ex['type'],
                'muscle_group': ex['muscle']
            }
        )


def remove_abdominal_exercises(apps, schema_editor):
    """Remove os exercícios de abdominal (para rollback)"""
    Exercise = apps.get_model('tracker', 'Exercise')

    exercise_names = [
        'Abdominal (Crunch)',
        'Sit-up',
        'Abdominal Supra',
        'Abdominal Infra (Leg Raise)',
        'Abdominal Oblíquo',
        'Prancha Lateral (Side Plank)',
        'Mountain Climbers',
        'Russian Twist',
        'Bicicleta (Bicycle Crunch)',
    ]

    Exercise.objects.filter(name__in=exercise_names, user=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_workouttemplate_workout_type'),
    ]

    operations = [
        migrations.RunPython(add_abdominal_exercises, remove_abdominal_exercises),
    ]
