# Generated by Django 5.2.8 on 2025-12-05 03:18

from django.db import migrations


def fix_squat_names(apps, schema_editor):
    """
    Corrige os nomes dos exercícios de agachamento:
    - Back Squat não é agachamento livre, é agachamento com barra nas costas
    - Front Squat é agachamento com barra na frente
    - Agachamento Livre é o squat sem peso (bodyweight)
    """
    Exercise = apps.get_model('tracker', 'Exercise')

    # 1. Corrigir Back Squat (era "Agachamento Livre (Back Squat)")
    try:
        back_squat = Exercise.objects.get(name='Agachamento Livre (Back Squat)', user=None)
        back_squat.name = 'Back Squat (Agachamento com Barra nas Costas)'
        back_squat.save()
    except Exercise.DoesNotExist:
        pass

    # 2. Corrigir Front Squat para ficar consistente
    try:
        front_squat = Exercise.objects.get(name='Agachamento Frontal (Front Squat)', user=None)
        front_squat.name = 'Front Squat (Agachamento com Barra na Frente)'
        front_squat.save()
    except Exercise.DoesNotExist:
        pass

    # 3. Adicionar Agachamento Livre (sem peso)
    Exercise.objects.get_or_create(
        name='Agachamento Livre (Squat)',
        user=None,
        defaults={
            'exercise_type': 'calisthenics',
            'muscle_group': 'Pernas'
        }
    )


def reverse_squat_names(apps, schema_editor):
    """Reverte as mudanças (para rollback)"""
    Exercise = apps.get_model('tracker', 'Exercise')

    # Reverter para nomes antigos
    try:
        back_squat = Exercise.objects.get(name='Back Squat (Agachamento com Barra nas Costas)', user=None)
        back_squat.name = 'Agachamento Livre (Back Squat)'
        back_squat.save()
    except Exercise.DoesNotExist:
        pass

    try:
        front_squat = Exercise.objects.get(name='Front Squat (Agachamento com Barra na Frente)', user=None)
        front_squat.name = 'Agachamento Frontal (Front Squat)'
        front_squat.save()
    except Exercise.DoesNotExist:
        pass

    # Remover agachamento livre
    Exercise.objects.filter(name='Agachamento Livre (Squat)', user=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_add_abdominal_exercises'),
    ]

    operations = [
        migrations.RunPython(fix_squat_names, reverse_squat_names),
    ]
