# Generated by Django 5.2.8 on 2025-12-03 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='analysis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['user', '-created_at'], name='vision_ai_a_user_id_8eea27_idx'),
        ),
    ]
