# Generated by Django 5.2.8 on 2025-12-02 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('motivation', 'Motivação'), ('warning', 'Alerta/Cuidado'), ('advice', 'Conselho'), ('celebration', 'Celebração'), ('nutrition', 'Nutrição'), ('training', 'Treino'), ('habit', 'Hábito'), ('mental', 'Saúde Mental')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.IntegerField(default=1, help_text='1=Baixa, 2=Média, 3=Alta')),
                ('context_data', models.JSONField(blank=True, help_text='Dados que levaram a este insight', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insight da IA',
                'verbose_name_plural': 'Insights da IA',
                'ordering': ['-created_at', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_type', models.CharField(blank=True, choices=[('INTJ', 'INTJ - Arquiteto'), ('INTP', 'INTP - Lógico'), ('ENTJ', 'ENTJ - Comandante'), ('ENTP', 'ENTP - Inovador'), ('INFJ', 'INFJ - Conselheiro'), ('INFP', 'INFP - Mediador'), ('ENFJ', 'ENFJ - Protagonista'), ('ENFP', 'ENFP - Ativista'), ('ISTJ', 'ISTJ - Logístico'), ('ISFJ', 'ISFJ - Defensor'), ('ESTJ', 'ESTJ - Executivo'), ('ESFJ', 'ESFJ - Cônsul'), ('ISTP', 'ISTP - Virtuoso'), ('ISFP', 'ISFP - Aventureiro'), ('ESTP', 'ESTP - Empreendedor'), ('ESFP', 'ESFP - Animador')], max_length=4, null=True)),
                ('disc_type', models.CharField(blank=True, choices=[('D', 'Dominância - Direto, Resultados, Firmeza'), ('I', 'Influência - Entusiasmo, Ação, Encorajamento'), ('S', 'Estabilidade - Paciência, Lealdade, Calma'), ('C', 'Conformidade - Precisão, Exatidão, Expertise'), ('DI', 'Dominância + Influência'), ('DS', 'Dominância + Estabilidade'), ('DC', 'Dominância + Conformidade'), ('IS', 'Influência + Estabilidade'), ('IC', 'Influência + Conformidade'), ('SC', 'Estabilidade + Conformidade')], max_length=2, null=True)),
                ('enneagram_type', models.CharField(blank=True, choices=[('1', 'Tipo 1 - O Perfeccionista'), ('2', 'Tipo 2 - O Ajudador'), ('3', 'Tipo 3 - O Realizador'), ('4', 'Tipo 4 - O Individualista'), ('5', 'Tipo 5 - O Investigador'), ('6', 'Tipo 6 - O Leal'), ('7', 'Tipo 7 - O Entusiasta'), ('8', 'Tipo 8 - O Desafiador'), ('9', 'Tipo 9 - O Pacificador')], max_length=1, null=True)),
                ('enneagram_wing', models.CharField(blank=True, help_text='Ex: 3w2, 7w6', max_length=10)),
                ('goals', models.TextField(blank=True, help_text='Objetivos principais do usuário')),
                ('challenges', models.TextField(blank=True, help_text='Principais desafios e dificuldades')),
                ('motivation_style', models.TextField(blank=True, help_text='O que te motiva? Como você gosta de ser motivado?')),
                ('triggers', models.TextField(blank=True, help_text='Gatilhos que levam a recaídas ou comportamentos negativos')),
                ('preferred_communication', models.CharField(choices=[('direct', 'Direto ao ponto'), ('supportive', 'Encorajador e positivo'), ('analytical', 'Detalhado e analítico'), ('motivational', 'Motivacional e inspirador')], default='supportive', max_length=50)),
                ('ai_coaching_enabled', models.BooleanField(default=True, help_text='Ativar coaching com IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
