# Generated by Django 5.2.8 on 2025-12-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Data de nascimento', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.FloatField(blank=True, help_text='Altura em centímetros', null=True),
        ),
    ]
